version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=my-elasticsearch-cluster
      - discovery.type=single-node

      - network.host=0.0.0.0
      - http.port=9200

      - bootstrap.memory_lock=true
      - script.allowed_types=inline

      - ELASTIC_PASSWORD=user
      - ELASTIC_PASSWORD=123456

      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./src/es-data/elasticsearch/data:/usr/share/elasticsearch/data    
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./src/es-data/kibana/data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS:http://elasticsearch:9200
      - SERVER_HOSTS:0.0.0.0
      - ELASTICSEARCH_USERNAME=user
      - ELASTICSEARCH_PASSWORD="123456"
    depends_on: 
      - elasticsearch
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge
